spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: true
  datasource:
    platform: h2
  h2:
    console:
      enabled: true
      settings:
        trace: true
